name = "sveltekit-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"


# Use the latest Node.js version available on Cloudflare
node_compat = true


[build]
command = "npm run build"

# Routes
[site]
bucket = ".svelte-kit/cloudflare"
